### ISSUE TITLE
Update and correct docs for Operate Elasticsearch settings.

### ISSUE THREAD

**Issue by ralfpuchert** [camunda-cloud/camunda-cloud-documentation#433]
The documentation [part](https://docs.camunda.io/docs/components/operate/deployment/schema-and-migration/#schema) for Elasticsearch settings in Operate is outdated:

> ...
> To define the desired number of shards and replicas, define the following template:
> ...

Found in https://forum.camunda.io/t/operate-elastic-index-template/2576

The settings for shards and replicas are under the configuration keys: 
`camunda.operate.elasticsearch.numberOfShards` and `camunda.operate.elasticsearch.numberOfReplicas`

for example in application.yml:
```yaml
camunda.operate:
  elasticsearch:
    numberOfShards: 5
    numberOfReplicas: 3
```
